services:
  backend:
    build:
      context: .
      target: backend
    working_dir: /app/backend/tp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      context: .
      target: frontend-dev
    working_dir: /app/frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  frontend_node_modules:
